### ISSUE TITLE
Option to skip forks

### ISSUE THREAD

**Issue by aminya** [julia-actions/MassInstallAction.jl#14]
The forks do not need to have these bots installed separately.

**Comment by DilumAluthge** [comment]
Sure, sounds like a good option.

We definitely want users to be able to do either. Sometimes you do want to install workflows on forks.

How about a keyword argument `include_forks::Bool`? We can set the default value to `include_forks = false`.

Want to make a pull request?

**Comment by timholy** [comment]
This is easy now:
```julia
using GitHub
auth = authenticate(#= your-github-personal-access-token =#)   # don't ever post this publicly!
rs = filter(r -> !r.fork && r.language == "Julia", repos("username"; auth)[1]);
workflow = ...
for r in rs
    MassInstallAction.install(workflow, r; auth, other_args...)
end
```

See the new README and `?MassInstallAction.install`.
