### ISSUE TITLE
Typo in variable name error

### ISSUE THREAD

**Issue by mschauer** [julia-actions/MassInstallAction.jl#28]
https://github.com/julia-actions/MassInstallAction.jl/blob/a3468a661feb3349d8936e92ba5e56c663ea7381/src/public.jl#L131

**Comment by DilumAluthge** [comment]
Good catch - want to make a PR?

**Comment by mschauer** [comment]
I feel I just made hundreds... ;-)

**Comment by mschauer** [comment]
Thank you!
