### ISSUE TITLE
Hitting secondary GitHub rate limits

### ISSUE THREAD

**Issue by mattBrzezinski** [julia-actions/MassInstallAction.jl#40]
When attempting to install to an organization which has a lot of repositories in it you can hit the secondary GitHub [rate limits](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits).

In my example I was trying to mass deploy to the [JuliaCloud](https://github.com/JuliaCloud) organization which has 17 repositories. Below is what I had ran, and below that the error message returned:

```julia
using MassInstallAction

workflow = MassInstallAction.Workflow("BlueStyleFormatter", "blue_style_formatter.yml" => read("formatter2.yml", String))
MassInstallAction.install(workflow, "JuliaCloud"; token=ENV["GITHUB_AUTH"], cc = ["mattBrzezinski"])
```

```julia
ErrorException("Error found in GitHub reponse:\n\tStatus Code: 403\n\tMessage: You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later.\n\tDocs URL: https://docs.github.com/overview/resources-in-the-rest-api#secondary-rate-limits\n\tErrors: ")
```

The way to work around this would be to introduce a `sleep(1)` (much as we have done with the CompatHelper.jl [integration tests](https://github.com/JuliaRegistries/CompatHelper.jl/blob/1a1aae8eba95260b369fa40ed3247fc4dd815134/test/integration_tests.jl#L28)) and if that continues to arise issues introducing a retry setup.

**Comment by DilumAluthge** [comment]
Yeah, let's start with the `sleep`, and then we can think about a bounded retry loop with exponential backoff.
