### ISSUE TITLE
Switch to Github API?

### ISSUE THREAD

**Issue by asinghvi17** [julia-actions/MassInstallAction.jl#5]
https://github.com/JuliaDiffEq/DifferentialEquations.jl/pull/526#issuecomment-557154660

Chris and I made this script for DiffEq a while ago, would be way less network usage as well.

**Comment by DilumAluthge** [comment]
Sure, sounds good! Want to make a pull request?

**Comment by timholy** [comment]
@asinghvi17, do you mean that you should be able to pass a `repo`? That's doable now, so if that's what you meant, please close this.

**Comment by DilumAluthge** [comment]
Bump @timholy @asinghvi17 can this issue be closed?
